// <auto-generated />
namespace Podium.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class testingcompleteallsuccessful : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testingcompleteallsuccessful));
        
        string IMigrationMetadata.Id
        {
            get { return "201807032128454_testing complete, all successful"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
